### ISSUE TITLE
[Design] Change colourscheme for MakeMyIsland site

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#13]
Talking to the team today;

The team is suggesting a 3 coloured theme such as shades of blue, green and white. What do I need from them for this? I can send them a colour wheel you normally use if that would help, design team?

We should keep the logo as it is on the website for marketing purposes as it was developed through a competition.

**Comment by JenMysoc** [comment]
An update from the team:

![makemyislanddesigncolours](https://cloud.githubusercontent.com/assets/4170351/8982079/8dc61f0a-36b5-11e5-80ad-f06a354ddd08.png)

"Color scheme something similar to above with the design same as that on FIxMYStreet.
Similar to FIxMyStreet please add texture to the background"

**Comment by davea** [comment]
I've updated the colour scheme with colour values from their screenshot (http://makemyisland.staging.mysociety.org).

Obviously there is still work to be done on the contrast of the links and so on.

**Comment by zarino** [comment]
**Update:**

We're still discussing homepage designs, but this is the current favourite:

![option-3](https://cloud.githubusercontent.com/assets/739624/9170252/209e9b58-3f59-11e5-9810-c9a55f47e857.jpg)

It'll work something like the full-screen background image on http://collideosco.pe/reports

I have a high-res version of the logo, so that'll need to be put in, to replace the existing one with the dark blue gif fringe.
