### ISSUE TITLE
[Design] Add prominent social media sharing on makemyisland.mv report pages

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/fixmystreet-international#9]

**Comment by zarino** [comment]
More prominent than it is on fixmystreet.com. Maybe of equal prominence to "Provid[ing] an update"?

**Comment by zarino** [comment]
Further clarification: **Just Facebook.** No Twitter.

**Comment by zarino** [comment]
The simplest way to do this is with a plain link like:

https://www.facebook.com/sharer/sharer.php?u=http://www.makemyisland.mv/report/15

Which opens a window like:

![screen shot 2015-07-23 at 11 09 17](https://cloud.githubusercontent.com/assets/739624/8847908/2dc63f8e-312b-11e5-91c8-941c6528ff1e.png)

Note the pretty unappealing image Facebook picks up, and the text below it which, aside from the title, isn't about the issue at hand. Really we should sort those out too.

**Comment by zarino** [comment]
When it's shared, it looks like:

![screen shot 2015-07-23 at 11 31 53](https://cloud.githubusercontent.com/assets/739624/8848339/70b9f850-312e-11e5-8493-a676b9d64152.png)

The image is cropped. I wonder whether we should make it landscape, rather than square? Facebook's guidance on image aspect ratio: https://developers.facebook.com/docs/sharing/best-practices#images

**Comment by zarino** [comment]
Improving the OpenGraph tags to direct Facebook towards a better image and description is something that would benefit _all_ FMS installs, so I've opened a new ticket for it in the main repo: https://github.com/mysociety/fixmystreet/issues/1154
